    START TRANSACTION 

    CREATE TABLE USER (
        ID INT AUTO_INCREMENT PRIMARY KEY,
        USERNAME VARCHAR(100) UNIQUE NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP
        ENGINE=InnoDB;
    )

    CREATE TABLE    